# Generated by Django 5.1.2 on 2024-10-16 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_change", models.DecimalField(decimal_places=2, max_digits=10)),
                ("day_trade_rating", models.IntegerField()),
                ("swing_trade_rating", models.IntegerField()),
                ("scalping_rating", models.IntegerField()),
                ("position_trade_rating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SentimentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentiment_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("positive_mentions", models.IntegerField()),
                ("negative_mentions", models.IntegerField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.stock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundamentalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_cap", models.DecimalField(decimal_places=2, max_digits=20)),
                ("pe_ratio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("eps", models.DecimalField(decimal_places=2, max_digits=10)),
                ("dividend_yield", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.stock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank_type",
                    models.CharField(
                        choices=[
                            ("short-term", "Short Term"),
                            ("long-term", "Long Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ranking_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rank_date", models.DateField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.stock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moving_average",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("rsi", models.DecimalField(decimal_places=2, max_digits=5)),
                ("support_level", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "resistance_level",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.stock"
                    ),
                ),
            ],
        ),
    ]
