# Generated by Django 5.1.2 on 2024-10-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "stocks",
            "0002_remove_sentimentdata_stock_remove_stockranking_stock_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="scalping_rating",
            new_name="scalp_trade_rating",
        ),
    ]
